version: '3.9'

services:
  pca-viewer:
    build:
      context: .
      dockerfile: Dockerfile.viewer
    ports:
      - "8501:8501"
    volumes:
      - data-volume:/app/data
    depends_on:
      - pca-writer

  gui-app:
    build: .
    image: gui-app
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/app
    stdin_open: true
    tty: true

volumes:
  data-volume: